// Generated by gencpp from file turtlebot3_msgs/LandmarkDistance.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_MSGS_MESSAGE_LANDMARKDISTANCE_H
#define TURTLEBOT3_MSGS_MESSAGE_LANDMARKDISTANCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_msgs
{
template <class ContainerAllocator>
struct LandmarkDistance_
{
  typedef LandmarkDistance_<ContainerAllocator> Type;

  LandmarkDistance_()
    : name()
    , distance(0.0)  {
    }
  LandmarkDistance_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> const> ConstPtr;

}; // struct LandmarkDistance_

typedef ::turtlebot3_msgs::LandmarkDistance_<std::allocator<void> > LandmarkDistance;

typedef boost::shared_ptr< ::turtlebot3_msgs::LandmarkDistance > LandmarkDistancePtr;
typedef boost::shared_ptr< ::turtlebot3_msgs::LandmarkDistance const> LandmarkDistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator1> & lhs, const ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator1> & lhs, const ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2f8ddf8c9e39a28149179429f5ae342";
  }

  static const char* value(const ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2f8ddf8c9e39a28ULL;
  static const uint64_t static_value2 = 0x149179429f5ae342ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_msgs/LandmarkDistance";
  }

  static const char* value(const ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name #Name od the landmark\n"
"float64 distance #Distance to the landmark in meters\n"
;
  }

  static const char* value(const ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandmarkDistance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_msgs::LandmarkDistance_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_MSGS_MESSAGE_LANDMARKDISTANCE_H
